### ISSUE TITLE
Site - Install Fonts

### ISSUE THREAD

**Issue by megansoh** [longcao/wedding#1]
Login to www.typography.com with my username + password > Cloud Dashboard > Publish this Project to your server

<img width="786" alt="screen shot 2017-04-01 at 5 23 27 pm" src="https://cloud.githubusercontent.com/assets/13702084/24582539/f1c8178e-16ff-11e7-9fb6-de01226fa67f.png">

Follow heading guide:
<img width="867" alt="screen shot 2017-04-01 at 7 04 11 pm" src="https://cloud.githubusercontent.com/assets/13702084/24583105/07b094c8-170e-11e7-9467-23ef0ff05c98.png">

**Comment by longcao** [comment]
Resolved by https://github.com/longcao/wedding/commit/ae030ef674a1c360851fb975d24432af7c14100b and https://github.com/longcao/wedding/commit/4aad397d1571433eba59886e11b8165eb70ac860.

Font sizing isn't entirely settled yet since CSS classes from http://bulma.io/ clobbers the type styling for elements, will fix later.
